name: Deploy to Firebase

on: push

jobs:
    publish:
        name: Publish Images
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
        - uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20' # Specify your Node.js version

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11' # Specify your desired Python version
        - name: Setup virtual environment for functions deployment
          run: |
            cd functions
            python -m venv venv
            source venv/bin/activate
            python -m pip install -r requirements.txt
            cd ..
        - name: Install Dependencies
          run: npm install -g firebase-tools
        - name: Deploy
          run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"